server:
  port: 7402
spring:
  config:
    import: classpath:application-common.yml
  application:
    name: community
  mongodb:
    embedded:
      version: 5.0
  profiles:
    active: dev
  data:
    mongodb:
      username: cheeseocean
      password: mongo.cheeseocean.com
      host: localhost
      database: cheeseocean