spring:
  config:
    import: classpath:application-common-dev.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
dubbo:
  protocol:
    name: dubbo
    port: 17402
  registry:
    address: nacos://korea.cheeseocean.com:8848
    group: INTERNAL_SERVICE
  application:
    name: community
    register-mode: instance
  consumer:
    check: false