spring:
  datasource:
    username: root
    password: root
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/cheese_house
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database: h2
