server:
  port: 5147
  error:
    include-exception: on
spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
  profiles:
    active: dev
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
  output:
    ansi:
      enabled: detect
  mvc:
    throw-exception-if-no-handler-found: true
    locale: zh_CN

