version: "3.9"
services:
  nacos:
    image: nacos/nacos-server:2.0.3
    container_name: nacos
    env_file:
      - ./env/nacos.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    volumes:
      - "./init.d/nacos.properties:/home/nacos/init.d/custom.properties"
    restart: always
  mysql-nacos:
    container_name: mysql-nacos
    image: mysql:8.0.16d
    env_file:
      - ./env/mysql-nacos.env
  nginx:
    image: nginx:1.20
    container_name: nginx
networks:
  qisee-net:
    external: true