version: "3.9"
services:
  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6389:6389"
  es:
    image: elasticsearch:7.12.1
    container_name: es
    env_file:
      - ./env/elasticsearch.env
    ports:
      - "9200:9200"
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    env_file:
      - ./env/mysql.env
    ports:
      - "3306:3306"
networks:
  cheese-net:
    external: true