version: "3.9"
services:
  nacos:
    image: nacos/nacos-server
    container_name: nacos-qisee
    env_file:
      - ./env/nacos.env
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    volumes:
      - "./init.d/nacos.properties:/home/nacos/init.d/custom.properties"
    restart: always
  nginx:
    image: nginx:1.20
    container_name: nginx-qisee
networks:
  cheese-net:
    external: true