spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: google-client-id
            client-secret: google-client-secret
          github:
            client-id: fde35d307ba5dcbaf79b
            client-secret: 0fefd4eacb906d3c79736239dd6ff47c76999835
  application:
    name: gateway
  profiles:
    active: dev
  redis:
    client-type: lettuce
server:
  port: 7404
logging:
  level:
    org.springframework.cloud.gateway: DEBUG