spring:
  cloud:
    nacos:
      username: nacos
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true

  application:
    name: gateway
  redis:
    password: www.qisee.cn
    client-type: lettuce
server:
  port: 51471