spring:
  cloud:
    nacos:
      username: nacos
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
      discovery:
        locator:
          enabled: true


  application:
    name: gateway
server:
  port: 51471