
store:
  host:
#    mysql-r2dbc: sfo.cheeseocean.com
    mysql-r2dbc: localhost
spring:
  r2dbc:
    password: mysql.cheeseocean.com
    username: cheeseocean
    name: cheeseocean
    url: r2dbc:pool:mysql://${store.host.mysql-r2dbc}:3306/cheeseocean
  config:
    import: classpath:application-common-dev.yml