spring:
  datasource:
    username: cheeseocean
    password: mysql.cheeseocean.com
    url: jdbc:mysql://127.0.0.1:3306/cheeseocean
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    generate-ddl: true
    show-sql: true
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    password: redis.cheeseocean.com
