server:
  servlet:
    session:
      cookie:
        name: SESSION
  error:
    include-exception: on
spring:
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: detect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    locale: zh_CN
  redis:
    client-name: luttece