spring:
  datasource:
    username: root
    password: xc514xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://korea.cheeseocean.com:3306/cheeseocean
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    generate-ddl: true
    show-sql: true
  cloud:
    nacos:
      server-addr: sfo.cheeseocean.com
      username: nacos
  redis:
    host: sfo.cheeseocean.com
    password: cheeseocean.com
