server:
  port: 7401
  error:
    include-exception: on
spring:
  application:
    name: core
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
  profiles:
    active: dev
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: detect
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    locale: zh_CN
  redis:
    client-name: luttece
  config:
    import: classpath:application-common.yml