server:
  port: 7401

spring:
  application:
    name: core
  config:
    import: classpath:application-common.yml
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
  profiles:
    active: dev