spring:
  datasource:
    username: cheese
    password: hellocheese
    url: jdbc:mysql://localhost:3306/cheese_house?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    generate-ddl: false
    show-sql: false