server:
  port: 7401
  error:
    include-exception: on
spring:
  application:
    name: core
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
  profiles:
    active: dev
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
  output:
    ansi:
      enabled: detect
  mvc:
    throw-exception-if-no-handler-found: true
#  sql:
#    init:
#      enabled: true
#      schema-locations: classpath:createAclSchemaMySQL.sql
#      encoding: UTF-8
  web:
    locale: zh_CN
  redis:
    client-name: luttece
    password: cheeseocean.com
